name: ignitia
description: IGNITIA – Universal Student Career & Learning Companion

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  
  # Utils
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  
  # Icons
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
